### ISSUE TITLE
A question about the Docker networking setup

### ISSUE THREAD

**Issue by breezykermo** [polyzos/stream-processing-with-apache-flink#3]
Hi there- thank you so much for this repo, and the forthcoming book! I'm looking forward to it.

I want to ask a question about how the networking is working to clarify my understanding on the Flink cluster setup. Please let me know if GitHub is the wrong place to ask this question, and if there is anywhere else that I could ask it!

I understand that the `JobManager` has two ports exposed to the host machine, 8081 for the web interface and 9249 for Flink internal metrics reporting. Each of the `TaskManager` containers then map from 9249 internally to 9250 and 9251 respectively to similarly report metrics to the host.

But don't the two `TaskManager` containers also have to communicate with each other (as per [the documentation for standalone clusters](https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/config/#hosts-and-ports), and as shown in [this deep dive](https://flink.apache.org/2019/06/05/a-deep-dive-into-flinks-network-stack/))?

Many thanks again, and apologies if this is a straightforward question!

**Comment by polyzos** [comment]
Hi there @breezykermo 
All the different components are run within the same docker network, which means they can communicate with each other.

When creating the cluster you can also notice the `jobmanager.rpc.address: jobmanager` is set - and jobmanager is basically the way for the taskmanager containers to identify the master node.

After registering themselves to the jobmanager they know about each other through service discovery and they are able to communicate and exchange data when needed.

Port `9249` is just for scraping the metrics.

**Comment by breezykermo** [comment]
Ah okay, this makes sense. Thank you!
