### ISSUE TITLE
Missing kafka environment variables

### ISSUE THREAD

**Issue by erkansirin78** [polyzos/stream-processing-with-apache-flink#4]
When I tried kafka got this error
ERROR ==> Kafka haven't been configured to work in either Raft or Zookeper mode. Please make sure at least one of the modes is configured.

To solve I had to add `KAFKA_CFG_PROCESS_ROLES: controller,broker` environment variable

**Comment by polyzos** [comment]
Hi @erkansirin78 thanks for this.
I realized I'm using the `latest` tag and the image might have gotten some updates I'm not aware of.
